name: Fly Deploy
on:
  push:
    branches: ["master"]
    paths:
      - server/**
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      # cd into server directory
      - name: Change directory
        run: cd server
      # Deploy to Fly
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --app ${{ secrets.FLY_APP_NAME }} --remote-only"
