name: Fly Deploy
on:
  push:
    branches: ["master"]
    paths:
      - server/**
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      # cd into server directory and deploy to Fly
      - name: Deploy to Fly
        run: |
          cd server
          superfly/flyctl-actions@1.1 deploy --app ${{ secrets.FLY_APP_NAME }}
